homeassistant:
  name: Home
  latitude: !secret location_home_lat
  longitude: !secret location_home_long
  elevation: !secret location_home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm

  customize: !include customize.yaml

config:

group: !include groups.yaml

zwave:
  usb_path: /dev/ttyACM0
#  config_path: /home/homeassistant/.homeassistant/config


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

# enable the iOS app
# https://home-assistant.io/docs/ecosystem/ios/
ios:
